apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oem
resources:
  - source.yaml
  - api
  - bootnode
  - validator-0
  - validator-1
  - ipfs-bootnode
  - nginx
configMapGenerator:
  - name: oem-values
    files:
      - values-bootnode.yaml=bootnode/values.yaml
      - values-api.yaml=api/values.yaml
      - values-validator.yaml=values-validator.yaml
      - values-ipfs-bootnode.yaml=ipfs-bootnode/values.yaml
      - values-nginx.yaml=nginx/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true