apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: t2
resources:
  - source.yaml
  - nginx
configMapGenerator:
  - name: t2-values
    files:
      - values-nginx.yaml=nginx/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true