---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc-substrate
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp2
  encrypted: "true"
