logLevel: info
selfAddress: 5Gh5cFC3sPS7pK8SN41Ytp6VFsMyPpvKxtrrcLpkf19u9W83
externalSqncNode:
  host: magenta-sqnc-node-0
  port: 9944
auth:
  clientId: 'l3'
  publicUrlPrefix: "https://auth.dsch-l3.com/realms/capacity/protocol/openid-connect"
  internalUrlPrefix: "http://keycloak.keycloak.svc.cluster.local/realms/alice/protocol/openid-connect"
ingress:
  enabled: false
  ingressClassName: nginx-capacity
  hostname: capacity.dsch-l3.com
node:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
