logLevel: trace
userUri: //Alice
externalSqncNode:
  host: alice-node-sqnc-node-0
  port: 9944
externalSqncIpfs:
  host: alice-ipfs-sqnc-ipfs-api
  port: 5001
externalSqncIdentity:
  host: alice-identity-service-sqnc-identity-service
  port: 3000
ingress:
  host: localhost
  paths:
    - path: "/alice/sqnc-matchmaker-api/(.*)"
      pathType: Prefix
node:
  enabled: false
