apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demandb
resources:
  - blue-node
  - cyan-node
  - ipfs-node
  - chainspec-configmap.yaml
  - source.yaml
configMapGenerator:
  - name: demandb-values
    files:
      - values-blue.yaml=blue-node/values.yaml
      - values-cyan.yaml=cyan-node/values.yaml
      - values-ipfs.yaml=ipfs-node/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
