config:
  logLevel: info
ingress:
  className: nginx-oem
dscpIpfs:
  enabled: true
  config:
    logLevel: info
    ipfsLogLevel: fatal
    ipfsBootNodeAddress: /dns4/oem-ipfs-bn-dscp-ipfs-swarm.oem.svc.cluster.local/tcp/4001/p2p/12D3KooWFDxTkVkRx3CRRVqg9s94NkFDgqkVEN7Fk92wj7TyZxbQ
    ipfsSwarmAddrFilters:
      - /ip4/100.64.0.0/ipcidr/10
      - /ip4/169.254.0.0/ipcidr/16
      - /ip4/192.0.0.0/ipcidr/24
      - /ip4/192.0.2.0/ipcidr/24
      - /ip4/192.168.0.0/ipcidr/16
      - /ip4/198.18.0.0/ipcidr/15
      - /ip4/198.51.100.0/ipcidr/24
      - /ip4/203.0.113.0/ipcidr/24
      - /ip4/240.0.0.0/ipcidr/4
      - /ip6/100::/ipcidr/64
      - /ip6/2001:2::/ipcidr/48
      - /ip6/2001:db8::/ipcidr/32
      - /ip6/fc00::/ipcidr/7
      - /ip6/fe80::/ipcidr/10
  storage:
    storageClass: ebs-sc-ipfs
    dataVolumeSize: 20
  dscpNode:
    enabled: true
    node:
      chain: inteli-stage
      role: full
      perNodeServices:
        setPublicAddressToExternal:
          enabled: false
      keys:
        - type: aura
          scheme: sr25519
        - type: gran
          scheme: ed25519
      flags:
        - "--rpc-external"
        - "--ws-external"
        - "--rpc-methods=Unsafe"
        - "--rpc-cors=all"
        - "--unsafe-ws-external"
        - "--unsafe-rpc-external"
        - "--pruning 100"
        - "--bootnodes '/dns4/oem-bn-dscp-node-0-rc-p2p.oem.svc.cluster.local/tcp/30333/p2p/12D3KooWCs3iTJXb1HtLfvXybNSP4tXhEjeKpoaKDmnvk3JDP9Hr'"
    image:
      tag: v3.0.1
    storageClass: ebs-sc-substrate
