apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: optimiser
resources:
  - green-node
  - yellow-node
  - identity-service
  - ipfs-node
  - nginx
  - source.yaml
configMapGenerator:
  - name: optimiser-values
    files:
      - values-green.yaml=green-node/values.yaml
      - values-yellow.yaml=yellow-node/values.yaml
      - values-ipfs.yaml=ipfs-node/values.yaml
      - values-identity-service.yaml = identity-service/values.yaml
      - values-nginx.yaml=nginx/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
