---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: shared-sync
  namespace: flux-system
spec:
  dependsOn:
    - name: aws-ebs-csi-driver-sync
      namespace: aws-ebs-csi-driver
  interval: 10m0s
  path: ./clusters/inteli-stage/shared/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
