---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacity-sync
  namespace: capacity
spec:
  interval: 1m
  path: ./clusters/l3-sqnc/capacity
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: optimiser-sync
  namespace: optimiser
spec:
  interval: 1m
  path: ./clusters/l3-sqnc/optimiser
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: order-sync
  namespace: order
spec:
  interval: 1m
  path: ./clusters/l3-sqnc/order
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-sync 
  namespace: cert-manager 
spec:
  interval: 1m
  path: ./clusters/l3-sqnc/cert-manager
  prune: true
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: certificates.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: issuers.cert-manager.io
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
