---
# DAVE: don't think need one, but wonder if we do or not need t
# o do sync for helm charts e.g. bitnami, have not seen that we do somewhere else like for others. e.g. secrets
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager 
  namespace: cert-manager
spec:
  chart: cert-manager  
  sourceRef:
    kind: HelmRepository
    name: bitnami
  prune: true
  interval: 10m0s
