logLevel: info
selfAddress: 12D3KooWSCufgHzV4fCwRijfH2k3abrpAJxTKxEvN1FDuRXA2U9x
externalSqncNode:
  host: charlie-node-sqnc-node-0
  port: 9944
externalOrigin: "http://localhost:3080"
externalPathPrefix: "charlie/sqnc-identity-service"
authType: NONE
ingress:
  hostname: localhost
  paths:
    - path: /charlie/sqnc-identity-service/(.*)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
node:
  enabled: false
