watchIngressWithoutClass: true
scope:
  enabled: true
ingressClassResource:
  name: nginx-optimiser
  default: false
service:
  type: LoadBalancer
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
    external-dns.alpha.kubernetes.io/hostname: optimiser.dsch-l3.com
nodeSelector:
  kubernetes.io/os: linux
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Equal
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Equal
containerPorts:
  http: 80
  https: 443
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: optimiser
