logLevel: info
paths:
  - http://bob-identity-service-sqnc-identity-service:3000/api-docs
  - http://bob-sqnc-matchmaker-api:3000/api-docs
baseUrl:
  - http://localhost:3080/bob/
apiPublicUrlPrefix: /bob
oauthClientId: "bob-swagger"
oauthAppName: "Bob Swagger"
oauthUsePkce: true
ingress:
  hostname: localhost
  paths:
    - path: /bob/(api-docs(/.*)?)
      pathType: Prefix
    - path: /bob/(swagger(/.*)?)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
securitySchema:
  name: "oauth2"
  type: "oauth2"
  enabled: true
  oauth2:
    flows:
      - authorizationCode
      - clientCredentials
    authorizationUrl: "/auth/realms/simple/protocol/openid-connect/auth"
    tokenUrl: "/auth/realms/simple/protocol/openid-connect/token"
    refreshUrl: "/auth/realms/simple/protocol/openid-connect/token"
    scopes: {}
