config:
  logLevel: info
  selfAddress: 12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD
  externalNodeHost: bob-node-dscp-node-0
  auth:
    jwksUri: https://inteli.eu.auth0.com/.well-known/jwks.json
    audience: inteli-dev
    issuer: https://inteli.eu.auth0.com/
    tokenUrl: https://inteli.eu.auth0.com/oauth/token
ingress:
  paths:
    - "/bob/dscp-identity-service/(.*)"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
dscpNode:
  enabled: false
