---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: alice-sync
  namespace: dscp
spec:
  interval: 1m0s
  path: ./clusters/kind-cluster/alice
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bob-sync
  namespace: dscp
spec:
  interval: 1m0s
  path: ./clusters/kind-cluster/bob
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: charlie-sync
  namespace: dscp
spec:
  interval: 1m0s
  path: ./clusters/kind-cluster/charlie
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
