apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel
  namespace: otel
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.82.0"
      sourceRef:
        kind: HelmRepository
        name: otel
        namespace: otel
  valuesFrom:
    - kind: ConfigMap
      name: otel-values
      valuesKey: values.yaml
