apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
  namespace: keycloak
data:
  values.yaml: 
    keycloakConfigCli:
      enabled: true
      configuration:
        realm.json: |
          {
            "enabled": true,
            "realm": "simple",
            "registrationAllowed": true
          }
      
