---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-broadcom
  namespace: keycloak
spec:
  type: "oci"
  interval: 1m
  url: oci://registry-1.docker.io/bitnamicharts