keycloakConfigCli:
  enabled: true
  configuration:
    realm.json: |
      {
        "enabled": true,
        "realm": "simple",
        "registrationAllowed": true
      }
httpRelativePath: /auth/
proxy: edge
ingress:
  enabled: true
  hostname: localhost
extraEnvVars:
  - name: KC_HOSTNAME_PATH
    value: /auth/
  - name: KC_HOSTNAME_PORT
    value: "3080"
  - name: KC_HOSTNAME_ADMIN_URL
    value: "http://localhost:3080/auth/admin/"
  # path: /auth(/.*)
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$1
# adminIngress:
#   enabled: true
#   hostname: localhost
#   path: /keycloak-admin(/.*)
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$1

