keycloakConfigCli:
  enabled: true
  configuration: {}
httpRelativePath: /auth/
proxy: edge
ingress:
  enabled: true
  hostname: localhost
extraEnvVars:
  - name: KC_HOSTNAME_PATH
    value: /auth/
  - name: KC_HOSTNAME_PORT
    value: "3080"
  - name: KC_HOSTNAME_ADMIN_URL
    value: "http://localhost:3080/auth/"
  - name: KC_HOSTNAME_URL
    value: "http://localhost:3080/auth/"
  - name: KC_HOSTNAME_DEBUG
    value: "true"
