installCRDs: true
global:
  imagePullSecrets:
    - name: dockerhub
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: cert-manager
    relabelings:
      - action: replace
        sourceLabels: [namespace]
        targetLabel: kubernetes_namespace