config:
  logLevel: info
ingress:
  className: nginx-t1
vitalamIpfs:
  enabled: true
  storage:
    storageClass: ebs-sc-ipfs
    dataVolumeSize: 20
  config:
    logLevel: info
    ipfsLogLevel: fatal
    ipfsBootNodeAddress: /dns4/oem-ipfs-bn-vitalam-ipfs-swarm.oem.svc.cluster.local/tcp/4001/p2p/12D3KooWJ1ZBoSYADNep8S23MPRKYG4M4epih6Xug4pkY4dL22hb
    ipfsSwarmAddrFilters:
      - /ip4/100.64.0.0/ipcidr/10
      - /ip4/169.254.0.0/ipcidr/16
      - /ip4/192.0.0.0/ipcidr/24
      - /ip4/192.0.2.0/ipcidr/24
      - /ip4/192.168.0.0/ipcidr/16
      - /ip4/198.18.0.0/ipcidr/15
      - /ip4/198.51.100.0/ipcidr/24
      - /ip4/203.0.113.0/ipcidr/24
      - /ip4/240.0.0.0/ipcidr/4
      - /ip6/100::/ipcidr/64
      - /ip6/2001:2::/ipcidr/48
      - /ip6/2001:db8::/ipcidr/32
      - /ip6/fc00::/ipcidr/7
      - /ip6/fe80::/ipcidr/10
  vitalamNode:
    enabled: true
    node:
      chain: inteli-stage
      role: light
      perNodeServices:
        setPublicAddressToExternal:
          enabled: false
      keys:
        - type: aura
          scheme: sr25519
        - type: gran
          scheme: ed25519
      flags:
        - "--rpc-external"
        - "--ws-external"
        - "--rpc-methods=Unsafe"
        - "--rpc-cors=all"
        - "--unsafe-ws-external"
        - "--unsafe-rpc-external"
        - "--bootnodes '/dns4/oem-bn-vitalam-node-0-rc-p2p.oem.svc.cluster.local/tcp/30333/p2p/12D3KooWQSy2rqKyrkyqnniFkLg3A8UFn6ChLBoRxj4LRoyGgUnf'"
    image:
      tag: v2.9.3
    storageClass: ebs-sc-substrate