apiVersion: v1
data:
    password: ENC[AES256_GCM,data:oGhr4IQo4OTboSkAXrRD40qDLvHBlMJ2,iv:esylI435+VE9GZwbDEmE4BNOC9Oogf9CwksVwcVM/yY=,tag:oY6LoLlO3O0Z3jrnPPy8KA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keycloak-admin-creds
    namespace: keycloak
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-29T10:48:16Z"
    mac: ENC[AES256_GCM,data:q9zDe47SsQsU65PObKEpqZCsu+W9uUTYJu+kf+McG7S0UQIkzq/44MtdHUXWhTQDuxmCCfn9wvhn1cXUo1U97tMnBtM3W7nBZosFN4AtKzb1floFgwR2IQu/i7OVWUBnhCsn25SsIsPhmqWzafcbVR9WWRVSwmoQsUtK2j/6+Oo=,iv:QBrLg/tlqRme/m5lU5/JvIFjhrsx7uVPNlsm0tn4320=,tag:Qk3PMehQAGLhU4mnGZB1OA==,type:str]
    pgp:
        - created_at: "2024-05-29T10:48:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWK9rONmXZEsSAQdAZqBtcVBUfmm07+fJkz6uNJQi6g9VwfWrUuavBFgC+HYw
            3Q5oFcxwupTAog3wSJGapuMv8GzuM5fSjIR7ToLzusOZKLfnt+Eo7kYaZ6MaeCx3
            1GgBCQIQ2XsabXc0l0q3e1JplU4eSP6CItD9+58qAmqQlVtJjfYEeWsyu9dhsorx
            oJgiTD0FPPdHvKAgs8rD21iFBHrWlWGwoXs4O/o+VQMGomXRVYNnYgFO1vtMQUaa
            Ul3DLxRqon2O3g==
            =s5my
            -----END PGP MESSAGE-----
          fp: BC3A767578FF432C7414DE6A73A07B99E207F7AF
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
