apiVersion: v1
data:
    account_seed: ENC[AES256_GCM,data:TFinG3TwxOnxiqk75JJtNlbtdZhKgYtaEtDXXEjbAm6aBT2hWnOQWf/JmGkPdlMxT7aWV2G3wfPM81sXNxb73Bgnis8oXZZfFFpLm4wPY5Mxy7z64U6KkV+feEIvugLhPzb8FXcsHFE=,iv:RSqAai/ZlsVJEI0cnoVXOnM85sInehhAQ+axmNSFMXc=,tag:oswgAq2KUuQ7b/Qr36FHCQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: order-keys
    namespace: order
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-11T11:41:13Z"
    mac: ENC[AES256_GCM,data:pigYZrijrNgdXWD7VJY4Ttur6Owxy2U3encohJGB+tzd5rSU9rVaF1RU2c5d+SvaFfLQJKfSOYeYVCZfmjXnpKYh97w/NqhLvkIGNUIiqzZH7WSX6B/1DemKOpZh7XKMAtY6lBQMKMkxXj+hf/Bb+0g9oVqC79J2uTqFCe+KV88=,iv:EEm2rDoWYg9Ju0uZhEDmFdtrQDD+HBD1Mwgy6isnbb8=,tag:RPSGZc89w7HWzrGtaQS7TQ==,type:str]
    pgp:
        - created_at: "2024-04-11T11:41:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DWK9rONmXZEsSAQdAkUe9/GtNTpUZ9pp4vMn7aLmCdjdJtDoPrHGAHIQFRTEw
            oSyQUCVe5kKuW9qPXxOHZbvPKMKntthAZ+R6ZSjo+Hfkky77KupWFz9zKXIlP0vw
            1GYBCQIQ8W/NNNVDycLThgVAwb9liSA6zSKMleOJg6Hpy45yhmtKjG7qKzkACppA
            q3jkbs2I7EAgozsQT56Gd/v1+DXcxgqVZPAcK+WPkgqNA7YVObMmuk0WoSldqxuU
            vwYv4SwrY50=
            =Yz68
            -----END PGP MESSAGE-----
          fp: BC3A767578FF432C7414DE6A73A07B99E207F7AF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
