apiVersion: v1
data:
    privateKey: ENC[AES256_GCM,data:cV+VUPZyAUSWHx1JunzsBFwdBPRwcAwlt46Eqi51Z5zVVv/QYGQOXmr4v2H6730XB5wJMMBddlfEEHDjehZ1/cEnKbEEyOk0HQLRkLm19lfNXyHAxMST+ieWwDqLuIRpb3/JebpCLaYn4GLqruwj1eK873R3tIQBvifFUw==,iv:7PNFaqxfhR5OIRtCaxr4Iaj55Jldc0dD+g6Gxt+KWv8=,tag:yXcsOJLeMe5EiIMv7QJBoA==,type:str]
    publicKey: ENC[AES256_GCM,data:2QELpeUFOh22TZiJ9pttyZVqgHRPpMYhDTObQ37PG67tazn1ovE2kQH897kE5pZCu5fdQqxvOUvKZHx1R0ZdIFyyi26q8y+f,iv:EicPBTzbki3NzJBR4CbEP7RTmp8gViHKGUFH5Y57qNk=,tag:SJXjbZwrjjoLYuwoEVH8yg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: order-ipfs-keys
    namespace: order
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-17T14:18:42Z"
    mac: ENC[AES256_GCM,data:W3HGFbu0Q0vGFYg/h5Nt2ba9qmsJ3F+yuxU0xUEsztTFkiutAXDi1jrVZfYiFkGwDYElnNjKQz6Zna/KqDkhb+VrJ/NfKKpO9MXzz+AOwMmMjQnxXJsobpgWYtQznVy6jShEm+nx9Z/zwUL6hA8w7OKscCLBPFB18jY8HPWSDU8=,iv:DxqP2mAD7H4JKIXrx5jlu4XYv+ouTIMybY8BODeOPHQ=,tag:FiNUFu4E4s/fAcPzInrdBw==,type:str]
    pgp:
        - created_at: "2024-04-17T14:18:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWK9rONmXZEsSAQdAJo0c9dSX0RIqwDU26nqqwnpFEpjYQ201USHfdVu7ADcw
            jN2nwN97nnETHQM137Nav2vXbRAHnVpQ+rW+cN2V1UnzKryJ3hk3VPDykyLiGINA
            1GgBCQIQ69EfsAJQEMo6kTr6f1yyCG44M+43GcDR60zcPzPi5SJsudqPOn8JnH7O
            Wm6qRC73gwgGZ/MjdYhKnDexmZoJu6Dg4yd0QQdFQl9oZZWyd0YFudVvCytDmXw8
            kZ+moFjI2gLxPw==
            =qfgm
            -----END PGP MESSAGE-----
          fp: BC3A767578FF432C7414DE6A73A07B99E207F7AF
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
