---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: oathkeeper-sync
  namespace: dscp
spec:
  interval: 1m
  path: ./clusters/kind-cluster/infra/ory/oathkeeper
  dependsOn:
    - name: ory
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
