apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: loki
spec:
  interval: 1m
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
      version: "6.16.6"
  valuesFrom:
    - kind: ConfigMap
      name: promtail-values
      valuesKey: values.yaml
