apiVersion: v1
data:
    account_seed: ENC[AES256_GCM,data:FXi4XHu4mGwMyq1OpGXGuxq4bZ48aDNGeU+h1l0OV7bM5X4vX0qQ5CWzImvW8xnrbkeRwSg6G0u6w5SWd+Yt12ztswG8mU/pLaEuOLsaYcA0ix/x0IfNMhyYeLs6DwhckaENiY8nqj/GLywmJHnthInrUrg=,iv:v894kEqU/JSNTB+u3hnCEliwQGydJwz0TTFVVW08m0k=,tag:2N4xe4D320GJ/lZlod8dRg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cyan_demandb_authority_account
    namespace: demandb
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-12T12:09:53Z"
    mac: ENC[AES256_GCM,data:WI/gIBKhT9OamwrNjBShvt/CZ8synj4B8aRQCDg8yeOQ3+3Rc2BhclBRsFozMeCnq1S1AB+6HFMBRNmDPYdxBycRmZYwVC0/L/0JedgesmoT19iIMQJykkrfXXJ2fGq+23jh22G+EYCqVpjNGG4gyR1gNCBcxWq0hnEnr5hBqO0=,iv:MAf96PHh3I7Iq4Sjc5bOoomjUxoBmTrWPoZoqZU7GtY=,tag:ZL9DaYD2h3e+I84CYMx2/g==,type:str]
    pgp:
        - created_at: "2025-03-12T12:09:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUwQKXS8ls7oSAQdAXcDa7cTz8kPFxLRnYvdlSv+6WLzLiHPKGOjVyVQvkAIw
            mw/Mzig5lRLVcbXWnDP1fCCUUE3EgCduXkwIabSEv0q1++DuVyjKX3PeUfQoHFLi
            1GYBCQIQnCQsTWptLJaAsunkdm+CVowg1ZBthOSXrXeX3UR9k7F+Z3XjqPW+HAwy
            3YGQCJ2CpT+ZP2ado3cgw9i1Cqc6xIoGbA9SCeBnVUJlcRAaAECBAtv+x4ToJ2cs
            lV3GFtSqJOM=
            =bP7f
            -----END PGP MESSAGE-----
          fp: 025EED3A1FBD8A5CE8A150C56DC71B2AE79A5F9B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
