apiVersion: v1
data:
    account_seed: ENC[AES256_GCM,data:NCfrfuc9opbG/LaBp8qv/Wj+zXPPChHt548ih4SPoNpQJmje5Y5EeM4cHdPE0TTJjaNB0b3+jRq4X/b7lUJCXvJSp1htajMMkJWUUCncEm8cEJ1OF+/aWkpuGJucR4bhM3T84Q==,iv:34y+zkPi2b0NBqxxfgwQeqJAqUynZtZpQ/H4LW1afdg=,tag:wSDhKELpvGKsmsf/ALxXVw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: demandb-keys
    namespace: demandb
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-06T14:57:12Z"
    mac: ENC[AES256_GCM,data:ELGpJX7RMB4CGDMNIhNmHwJRk/mp7YqrfZkMIwmD6I+nHRA4diWB4bJPm6kaV51bCE9N6Ikx1kEilMVKCHFvcuqlhDiYwPT0JFs9JAF+7MV/dXuijzRo9gutyH+WgZfVxeNMqunmKTUzC046eD61kpfpgiPMf3+4gJQa8YxI00M=,iv:1U4YOOgx7fVja1BOYc40yx9Ngygm6hD1/tfEJyFcU4I=,tag:lqxGfVp+wuG0zUWN7VJJ/w==,type:str]
    pgp:
        - created_at: "2025-02-06T14:57:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUwQKXS8ls7oSAQdAa3aON50epYL2Y9VXQsV4DcUEst3D3rgFnSAS3vx0eCEw
            Byadj36tVEVKUPA2Rk+PoqQETuGDsIKoq1pNVys8y+1ygTAcfHqOM9gWqj0gKCR3
            1GgBCQIQJuCAQZoqA6SWJcwW/0H9wULnzFDv+yqb8cXUddEwWWVnMAgT5iiqBnlM
            cpb6xDfDyzNAB2aa0Q+aWwdrNv/PtakjKpXU2vozFoKRJZUZ43kmrPyg+WsyUgsQ
            irC4igmSWwG03g==
            =gAgT
            -----END PGP MESSAGE-----
          fp: 025EED3A1FBD8A5CE8A150C56DC71B2AE79A5F9B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
