apiVersion: v1
data:
    grafana-client-secret: ENC[AES256_GCM,data:6ioQCMbi2+s4wcXhfgHjmcf3A5VocvrShYAHWSktTMAa2clpWK1XvKdqFbM=,iv:b/7eEufjije5sUftRPtgCAlZfqdTswV/kqa50BZ+B80=,tag:zEWdtqigB4dNjJYX1yjlVg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-client-secret
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-28T12:39:02Z"
    mac: ENC[AES256_GCM,data:f94iIyf0hlQZnQtVyocjC/hpluQYzLN/cJel+IeywQfk10S1mlzcnrVuGnGZkUWEfmGbsmwlvbyBYnqDkDVbs7FW0ic83+ddgIWqaM1ruppnlOUWdNFJV2qFfR/581xUPs2F5B+PxeT41kuWXOG3h/mtcU4WAANQqeRttcb8qU4=,iv:BBJ3QjJJBmpQzNPlJpmuvdWDvGC63SWlnuemlJBhQRI=,tag:fQp9ooWZwGKicY2SwSc4AQ==,type:str]
    pgp:
        - created_at: "2025-01-28T12:39:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUwQKXS8ls7oSAQdAi7xqWNCDCYtHHH8ijCuyFin+kMl6NZbVguTS11pi1mMw
            wqVbGi4y/mCnkRjhjsXqeAeG0xhZPLGbs4KFnrB39/Pt1wckl7wI163mrZO4Pu8m
            1GYBCQIQZgLmGKKsiVNt1dK63Ne5C/iMcufXl/qvw8UMfp3ybS53ldPP58/acRLB
            eqVwqHpticTQrusGyo+vBxSbIgTnTS/hcJTi68s/tCs78igRlpRhKJIQg496SUkv
            rodPytlpb28=
            =Ajtr
            -----END PGP MESSAGE-----
          fp: 025EED3A1FBD8A5CE8A150C56DC71B2AE79A5F9B
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
