apiVersion: v1
data:
    password: ENC[AES256_GCM,data:zrroMfegsdhnuKB5hgn4aUqfA1p17aX9Mq0FujrosF0OQ0GD6Z0IeKxYlmo=,iv:EsSnfQeHRcgiQSyj2Pa85VeSoL7go3Oe78PH5eJx8H0=,tag:KjZ4X7NrT720vhJO60VSLg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keycloak-postgres-password
    namespace: keycloak
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-28T12:34:39Z"
    mac: ENC[AES256_GCM,data:Qo4n5uwQQoYQ/ZibPihtyHJkllJwPu7vX5QmSwmQFs/uX7FUHLsh7gjRu/qd3WDg4OII6Ir+K1SZJV8PUDi/Li2O1qQtHPI1xwRaERsHYqgyWNk30ytpsToWObyEStSioNLJPvw8ou0LRh7v3FIwyfE5MsguDfBWCUnddmVTU8M=,iv:koHEA5p+fBcPZf56CfQ41S4+3ilgDLvx8+D+CgnRJSU=,tag:gR4EwEIwpvI32Svf374SlQ==,type:str]
    pgp:
        - created_at: "2025-01-28T12:34:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUwQKXS8ls7oSAQdAS40iaxfUpMRy02JnwO99C/sjvpTrmTiWPZnmw4CgHRQw
            ba8lykq4qc7eGpoz3S6ML1ekDY/D1Hj/7hIpWnTHFPtABM99O6Dp5DlZmjXtnW6w
            1GYBCQIQTZ+Wnf1RRY6R2ospfdViYgrNCzIOPWozNe4tgTSTTLg/z3GUBkoHZsRu
            gtj4naGoJEvRkyNLQYaAAHBn9BaImURLnNxcMGCf6yGhhn7BW1LBIV9jGLVsVYL+
            BKTg00O3tas=
            =XhSn
            -----END PGP MESSAGE-----
          fp: 025EED3A1FBD8A5CE8A150C56DC71B2AE79A5F9B
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
