apiVersion: v1
data:
    babe_seed: ENC[AES256_GCM,data:objKFkMiCGL1smpxipnBxCA9e0ha9capuIzPIx1wpsgUMm5isEwh5BybOIEB7yB1ziNKYDtga9lqfmAjGVIRuIkwuNnLuOyHTe5J+NaG3tu6VcbJK3A53dGP2MqtUGOmgSGtD/y2jy+l1ToB,iv:0+7K3/1QIHV3v6GPjBX54DNYy2C2aynHfjARSVkONaQ=,tag:ykygOYheAjOVfsJ0lnzLSg==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:axemDtFc3Ro5RAZM/aOw2DjSdvDTxfRobzyN1a7uIO+YqZlpaBT4gJJfC4ZKwffMmtNbCNzKvxUtvrD+at0laJ5nNgFx6hP/qntLyZy1OhCApeK+xvafE6UTvkVyNNiyQkYwYZh/mHo=,iv:IzmtgkIJ33fiyC1N6hT2nLhP9MfRn335hv1raaUU1vk=,tag:0xe2jVlN9Mv74qNHcI0wfA==,type:str]
    node_id: ENC[AES256_GCM,data:pPlBvkF3bkPB0od42HH4Ps0Pc1ov7mDCI99eGgAI9EhpoqzVDz9zlXZh3wNDYJmzx/jRAcoFpiRiUiAxkRHN9EvzWx66bPOgHZvMKnZOlZyGY4hHURBrSQ==,iv:C4XPny2QdSrhP/vlyajWxrCgFp85XN2PzmqyydPhQbE=,tag:TRJLjRqlTyGTG7FaWpWk6A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: yellow-keys
    namespace: match2
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-06T14:57:13Z"
    mac: ENC[AES256_GCM,data:d4MFJuJd6WsqJD6G7XXfFA6F0u0ocE6yad+0wjNWHTR1NbngV6n4uDKCknswW6LsLswH2Yq6US+wEuPrInfUrOi0kvzLn37WDSyT/3ftI33L2YTJwYPUmCfTMCTjNgDcirG62jkQ+0Ptar1BrxXMvr32VMsbSpmivRLogJo6VR8=,iv:fgVx4dhpkVeQFVgojrkUZ/E6h9DOdcgAspjWxSJwV04=,tag:HToTcWjHnI6v462dAARcnQ==,type:str]
    pgp:
        - created_at: "2025-02-06T14:57:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUwQKXS8ls7oSAQdA+NNxyiEuYjWm5Hn5TzysLngkdj8giMvpCF1QyPJ/oQow
            pTWIxWN2EwWxFHhSlnaALkLMzEb0rsqtGPf1JdMbn0BVUTCArVFHQiB+OPJwD08a
            1GgBCQIQiPyW2H28D/8+/VXquaFtbX2gHzgs0eqiBvT7v1LWZvDMM+h2NyfvmEF4
            qBhOEGTy0G9ujirH99rxLjP3ixTEIDxfgZ7yPJ4KMcQqJMr3vLU3EZ9+9E84keJ1
            ORnAaBw3/Tf9aQ==
            =x29i
            -----END PGP MESSAGE-----
          fp: 025EED3A1FBD8A5CE8A150C56DC71B2AE79A5F9B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
