apiVersion: v1
data:
    babe_seed: ENC[AES256_GCM,data:TLHJgkehYx0O17vtdEE+vYk/dwzZUfnEbIfoA511ZQqTR2pT7PVzxpRCCeWEgKxxIewGr1JoG9gu2djHHmpp9Qgl4edt4glMs8x6KG8uxpL/pKjtnsDstnU72uV4uTYHZHZWTQ==,iv:rfZM3zMpo3FYm9QlkmhtKN06XfQOW+tQQPKPKoJ4Vc0=,tag:vMPTLn67e4OFMg9Zz1aiXg==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:bDjwZeBtFDNGBXf7xOEE6jwQeXDto64TvGXi9cRJFS2w0tI0iVQlmoibuCbZ+prDG4Qz5X20sLDx1x3gHSObf69tboMKDuPssieIScMJ8VMh81+3szIBXaUbZqbgFrFk3T27Hv/0j+U=,iv:IzfaIKugYn640PjHxBG4cIKdIeG4YHMwzsjBmgoUhrc=,tag:ruigQjbKp2pCxFHbpEP+wQ==,type:str]
    node_id: ENC[AES256_GCM,data:gbEe5LoO5wPbufnHhJ3DBX7BHz9YE6Zfnw+/D9bWN34OS0LqVOK92596xup456UNVHT/00GDLDfFE4bDiszJbvPnYPPzjOF3/Y+/c3Cxbj6XK0ORu2JMJQ==,iv:dSwKtH0o9KwXt3WaviUxgJPJiXD68x4yevOpGojEm9M=,tag:4nfrnlj52fkQ116W9olq8g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: yellow-keys
    namespace: match2
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-12T14:38:38Z"
    mac: ENC[AES256_GCM,data:cyXmcWxmky4tYfXoZEpcWbe9KM0+H1gdpkOKOCXUMskte67D5VsPcMi8xogH48NEYNfvpEC/astzx8metSJuDJB90EZh3GBBwRr8M9S52fkbn/T8sGq4FjDzrsvyaHT+YhHTEzm7MzC5nmSvMuVFU3GE/F6QXtYe5QTlJ+UeKPs=,iv:/lHH06bjmj4a1rLNrTxNILmAtUcCNChQXe4rM4ebXIY=,tag:C8W2+wEByH4X8ndL6n5Tew==,type:str]
    pgp:
        - created_at: "2025-03-12T14:38:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUwQKXS8ls7oSAQdAFwqj3junxiGAskoLdO3vyoCkO692oMoXXb19aCjYIy4w
            v0k9Zd1apr1gYEBufFC5dDH75TQCyRxrgznBMKJk97NSVgEHDQNEHDtCs081cwvX
            1GgBCQIQmbzitAf7UUuB1M1EL+sf6TL8c8qRb7PdkLAL/SDitiRFXFtWxDtyNS82
            J8wt3n81gO+tLLCoM0X6x1M0q90etPE0G1wvlbei/S6qqAEm+dyojBUiT+jhOMwl
            cCJgsz3OK7tBFw==
            =+DXP
            -----END PGP MESSAGE-----
          fp: 025EED3A1FBD8A5CE8A150C56DC71B2AE79A5F9B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
