node:
  chain: inteli-stage
  role: validator
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  keys:
    - type: aura
      scheme: sr25519
    - type: gran
      scheme: ed25519
  flags:
    - "--rpc-external"
    - "--ws-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-ws-external"
    - "--unsafe-rpc-external"
    - "--bootnodes '/dns4/oem-bn-vitalam-node-0-rc-p2p.oem.svc.cluster.local/tcp/30333/p2p/12D3KooWBznYGcptH7Z4fwhHevGkGk41PJaKbvC2AfSvAutWeihc'"
storageClass: ebs-sc-substrate