logLevel: info
userUri: //Bob
externalSqncNode:
  host: bob-node-sqnc-node-0
  port: 9944
externalSqncIpfs:
  host: bob-ipfs-sqnc-ipfs-api
  port: 5001
externalSqncIdentity:
  host: bob-identity-service-sqnc-identity-service
  port: 3000

ingress:
  host: localhost
  paths:
    - path: /bob/(v1/attachment(/.*)?)
      pathType: Prefix
    - path: /bob/(v1/demandA(/.*)?)
      pathType: Prefix
    - path: /bob/(v1/demandB(/.*)?)
      pathType: Prefix
    - path: /bob/(v1/match2(/.*)?)
      pathType: Prefix
    - path: /bob/(v1/transaction(/.*)?)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
node:
  enabled: false
