config:
  logLevel: info
  externalNodeHost: bob-node-dscp-node-0
  externalIpfsHost: bob-ipfs-dscp-ipfs-api
  externalIpfsPort: 5001
  accountKey: //Bob
  externalUrl: "http://localhost:3080/bob/dscp-api/v3"
ingress:
  paths:
    - "/bob/dscp-api/(.*)"
dscpIpfs:
  enabled: false
dscpNode:
  enabled: false
