config:
  logLevel: info
  externalNodeHost: bob-node-dscp-node-0
  externalIpfsHost: bob-ipfs-dscp-ipfs-api
  externalIpfsPort: 5001
  accountKey: //Bob
ingress:
  className: nginx-bob
dscpIpfs:
  enabled: false
dscpNode:
  enabled: false
