node:
  chain: local
  role: validator
  dataVolumeSize: 5Gi
  customNodeKey: "0000000000000000000000000000000000000000000000000000000000000001"
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  flags:
    - "--rpc-external"
    - "--ws-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-ws-external"
    - "--unsafe-rpc-external"
    - "--alice"
    - "--prometheus-external"
    - "--telemetry-url 'ws://telemetry-shard.sqnc.svc.cluster.local/submit 1'"
  serviceMonitor:
    enabled: true
    interval: 10s
    scrapeTimeout: 10s
storageClass: standard
