logLevel: info
paths:
  - http://order-identity-service-sqnc-identity-service:3000/api-docs
  - http://order-matchmaker-api:3000/api-docs
baseUrl:
  - https://order.dsch-l3.com
ingress:
  ingressClassName: nginx-order
  enabled: false
  hostname: order.dsch-l3.com
  paths:
    - path: /(api-docs(/.*)?)
      pathType: Prefix
    - path: /(swagger(/.*)?)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
