---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bob-ipfs
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: dscp-ipfs
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: dscp-ipfs
  valuesFrom:
  - kind: ConfigMap
    name: bob-values
    valuesKey: values-dscp-ipfs.yaml
  interval: 10m
