config:
  nodeHost: bob-node-dscp-node-0
  nodePort: 9944
  privateKey: CAESQM0Tr9ABULiEY/eYlokv8Jmm51+bcdDgdtaQ+qfW5zWj2nnmxPqpR77onoXS5mmrYtD7o/AOaoidj5/mf6ZaQjE=
  publicKey: 12D3KooWRSDi5CRXMS7NfVwvLrGNTDbpJeShH4MdQ15rJCDbhWnD
  ipfsBootNodeAddress: /dns4/alice-ipfs-dscp-ipfs-swarm.alice.svc.cluster.local/tcp/4001/p2p/12D3KooWSD3ThKEecxkH6wttDYWnokJfuUhbMpdCrjkTSbNyHRnn
storage:
  storageClass: standard
  dataVolumeSize: 10
dscpNode:
  enabled: false
