apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: jaeger
spec:
  interval: 1m
  chart:
    spec:
      chart: jaeger
      version: "3.4.0"
      sourceRef:
        kind: HelmRepository
        name: jaeger
        namespace: jaeger
  valuesFrom:
    - kind: ConfigMap
      name: jaeger-values
      valuesKey: values.yaml
