---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ipfs
  namespace: demandb
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: blue-node
  chart:
    spec:
      version: 4.0.1
      chart: sqnc-ipfs
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: demandb-values
      valuesKey: values-ipfs.yaml
  interval: 10m
