apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
  namespace: dscp
data:
  values.yaml: |
    service:
      type: ClusterIP
      targetPorts:
        http: 80
        https: 443
    scope:
      enabled: true
    containerPorts:
      http: 80
      https: 443
      metrics: 10254
