apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: dscp
data:
  values.yaml: |
    watchIngressWithoutClass: true
    ingressClassResource:
      default: true
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    config:
      global-auth-url: "http://oathkeeper-api.dscp.svc.cluster.local/decisions$request_uri"
    service:
      type: NodePort
    nodeSelector:
      ingress-ready: "true"
      kubernetes.io/os: linux
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Equal
    containerPorts:
      http: 80
      https: 443
      metrics: 10254
