---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: optimiser-identity-service
  namespace: optimiser
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: yellow-node
  chart:
    spec:
      chart: sqnc-identity-service
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: capacity-values
      valuesKey: values-identity-service.yaml
  interval: 10m0s
