logLevel: info
selfAddress: 5HdXyANz5ySq8FPBxhdbm2d8FjPRKZHEAnNtypaAWix8BDRJ
externalSqncNode:
  host: yellow-node-sqnc-node-0
  port: 9944
authType: EXTERNAL
externalOrigin: "https://optimiser.dsch-l3.com"
ingress:
  ingressClassName: nginx-optimiser
  hostname: optimiser.dsch-l3.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
node:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
