hostNetwork: true
service:
  type: NodePort
ingressClassResource:
  name: nginx-alice
nodeSelector:
  ingress-ready: "true"
  kubernetes.io/os: linux
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Equal
scope:
  enabled: true
containerPorts:
  http: 80
  https: 443
  metrics: 10254
