---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oem-bn
  namespace: oem
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: vitalam-node
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: vitalam-node
  valuesFrom:
  - kind: ConfigMap
    name: oem-values
    valuesKey: values-bootnode.yaml
  - kind: Secret
    name: bn-keys
    valuesKey: node_id
    targetPath: node.customNodeKey
  - kind: Secret
    name: bn-keys
    valuesKey: aura_seed
    targetPath: node.keys[0].seed
  - kind: Secret
    name: bn-keys
    valuesKey: grandpa_seed
    targetPath: node.keys[1].seed
  interval: 10m0s
