node:
  chain: inteli-stage
  role: light
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  keys:
    - type: aura
      scheme: sr25519
    - type: gran
      scheme: ed25519
storageClass: ebs-sc-substrate