config:
  logLevel: info
  externalNodeHost: alice-node-dscp-node-0
  externalIpfsHost: alice-ipfs-dscp-ipfs-api
  externalIpfsPort: 5001
  accountKey: //Alice
ingress:
  paths:
    - "/alice/dscp-api/(v3/.*)$"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
#   className: nginx-alice
dscpIpfs:
  enabled: false
dscpNode:
  enabled: false
