apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:iKraI9nUp4JbYtu2AUeR/6pIF65UeLqfwj8qR2yech1uJUce8hn5I+KkIGEh4a+UVbvbGIaW2LhGx31tQ2gYQZcqG/tIgZRqj60Pcw+Jlg2hZFJfJOyv8MKrnY0VQw4lywX+tDEps5gXm3yWV3G4z9/ZhDY=,iv:i9t/yfyUwKipvZP4Hcq8FJhyZuQ3aa+V6dl4J8ckWUo=,tag:pn8JRP2jBkQkRoZ1/Ot1Yw==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:8VlnrEP8lDGI5A9j7q6PmTuud0tyyWbHj7opUEGZbsoef3Lmm9OGdo/ZTbnK629jMmf8nAuMIatcAVoyQhl9+PudMcFT58rR83FNB2/+U16G3tXwAf1uK+u4fpRYqoQGquBG1g==,iv:S+K4IFa3Lj3pldCKnx0v2i9kfYA9OsfkYF3kh+nZvRk=,tag:6Exks5QMCYCBm+GRBTGfdw==,type:str]
    node_id: ENC[AES256_GCM,data:uypBphJNSN05gWxVZMe/0I9yELy36yahOxCbsXSS+M3VRV+4k57uMZf39Lb1fDP8b0KEmMSI4B3kSc3bv88zw/vEYtH5YWliCpJbBtEbf0Kxj4b+VdvkPw==,iv:yla5YdBG5BGOXvbspD9dyERiKsaR2xnKRnNoDWHrVLY=,tag:0xHjMw7XqOQP6WnIFiO4kQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: api-ipfs-light-keys
    namespace: oem
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-14T08:56:11Z"
    mac: ENC[AES256_GCM,data:sc9kLwHFSK+Ww5z6hZitR8ztD608XppTyyhnS1gaoiTFbgJRuxJuQQijQGgtfhRSiB3r05cpzGkJwK1EitP9R2JKmKHOVD9cypDF6JwHajHd1/G7wrhi3srBdp8BE0faO2FN68vSjzaZl4tEwkuVGlcCtFIfs7TTy2aUAsCah/I=,iv:cD/J4lkqHeKiOp1mEwBJuYuiDumBulnQ5cQDVIm52y8=,tag:SchDkEaP/jH7TkZtZ9fV1A==,type:str]
    pgp:
        - created_at: "2022-02-14T08:56:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv/VPLUUJBDFa66IPWaABfGZxnnu960bTrOFEVec12nEDWO
            0JnoRwskkWzOEid/B/QwHBip0Ck46T2pH6r3gZpFVsOF4xvFPgAmL8GeVjO3Mlxc
            TRXyePs6z+rkk1nvkFZn6xnTAKq+hgmg7GJKBOfyBelxZMQC2yPAY6Yfc8h5s7M0
            xAR8n9QoNWyYh56vZYwuE5sFdo6v6JS50naRnTNDYGNnty7sV2QjcTuRJj6Vvz1B
            TnSuV/gC8eNCA88chjXbipLHLEqu4intsRAox34bRgMCSRU2FesutpmsKF+QIbM0
            Mv/CxUwMyNcw3ZFqTzbbOhbyCrrOc9NSmhBAqZEGDzBlgMwE7FByNumPTQGU1oq8
            5z4bw4xeZjNUBByLVPu13hI+OEzH/OWc4CUHswkC5wCSDD6bKvzxDZ2JyOWYbKPE
            RcI87+N/UocmgyoATRNteMbwey3NOaMuhG/BTJVjTqVcC+Bq38bhep30838RBHxG
            ESEnir2XUgBaCUudkYya0lwBtQGBDmlqamYoBlfrWojGNNjS5LKsUSZo+RV1UkMF
            jnMCgBZyz+rqDmH/FtR3bS5fNBjTDJ1rP4f1GL8skrM5eqn5KxKCRWfK57RepwG6
            +8NCyHVOpnvLrR7A3g==
            =x/D8
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
