apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:wrtymRnPxBBwxIDtsNLK7LqWvCQPkGUyxQC0SFMd+/OYwI7qHoNejKLGbH1zvPzklwYauc+DBwkvOkxx6iVguVpQMr9tSTfzVOBcO1TL2QT2mthf4eXVhUeIOycrpxf5LgCYWDkDRqbTWHBi,iv:PyGQ1jFRpHs346dPXjreADb8GiTZJgV2TIXq/+0/pMI=,tag:6B8RIZ5cb5GYw7OkbQpwUQ==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:uGZUx9bALjyhCdgbP5LzHcS9BgC9dqUl7m3+kl8mySG37k3Q1T7m0kF/EVTjF8UddNjFFrm6alwFb3+oBvNenssIw/pRxa2PJBO9Xsli8v1dyXebG5WXtjfuZ14uHqzpsGj8oYMg2II=,iv:c4MF2YDmr1CYQ0PNw4/Ce+0oHQaoQ4GJLURrH0lx6/4=,tag:nUOypZt1ysIQAl2VtSTZoQ==,type:str]
    node_id: ENC[AES256_GCM,data:q1FNyoFvCVBkDY/lR3geW3NQ+tvam9ls82M3l7LuhPrDdolsB9SGLVdnlguWMfUFOxasX30oKrgIXflJvjvnPau0hORzXDN7Kr2qNp4FupzXXobL0g1jNg==,iv:OG3uITW84Iqm+5mpYTW+8w9hy8Gj/H41Z7ONI5Nsy9U=,tag:tLqHNlaJMSIiMpVUlIQR2g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: api-ipfs-light-keys
    namespace: t2
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-10T10:55:45Z"
    mac: ENC[AES256_GCM,data:Xm6eojQorisD1NHTJldjD2MpzEwwVpzZOR8DozKzsm6WgOr3fUOskyGkfRZuwU4aNuyb0Ru2Y/+7gWy4rzuHo/duT2Nj67M9wTMwJX97YH1XhecuY7bm6Q17vm+APEV+BTPYTGFgZmI58lwxyPW7A5aAHYcTOOXjX8Dk3VoVvaI=,iv:XGY2wp/QezUa5bQJLvJm0m1rGFLpZ2kXgUyVrHdoh8U=,tag:+EYMCaFBwBR7ooiBjpHvJw==,type:str]
    pgp:
        - created_at: "2022-02-10T10:55:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv+PsA4gM5BtG2q+fCyebR/jO8ty7gD9M1umu7GXXTe/Mo+
            TW3GyxBLSs7m/22fUWKPwbU6d3iIPafB6jnjMzNRltX0qz27yjitBDSZyGcpzQ1i
            CPQAi3PbO9H1cDG0tm+9E+WKehUW5vcNC3IGCqZV5kMzsVRzFvXIaLZWs+X+EcK9
            EMgOa3xvEtmRr+7vO/yjdgzvesSd46AW7yGTuCuK7wyDzJTxX6m6jxwzqCuwu8cS
            L8WHhwLsVeOlCo7o5FCOl6HNYCZHQubznhIb3dteWPStwSmF+07CEyhHGjqloAQs
            7IZ2kKQYdQOKqH4t2Py6V1ZWPCSVZoGAOt5uV0Q9kAYWunbBGOwZr4JiPqKyVnVI
            k02VGoq1wQptnwfckr3m+P7G8SE4+UY0uH6kmrM0FRh3MNdZ/w+c75TFGyyiUiDi
            SjDN3xWUHwCHgSLRs+sBYZ/fvkqrsVwuuTER44QV6cOw9urKZ/I40WU4kZTso4yi
            l6LieAvDkpiQC5K2706U0l4BvjNvMTN0iDSNsE3qRdsegR4rgfdlaEurqEKN+kzm
            /EduRRO/Y6dUU1UPv3d6eZ11wAmpv080dkSoJjkWPA9GKZVdGdvQ2fZ3hoOGlBVo
            sdRGlGaM7v/PysvRdpJq
            =5XOs
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
