apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:VplJaoJw1/cG9KauxFvrCgIkE+5gyqGEcL9A9SHGcbPwsbtxG8Ht/0oZY2jD5Dj2jiwZOduN2QFFCrV8if5Jv2XyT6M7HR9sOb3zDxqwHqmkrkKfDd1r3P41kjMw3eJzUz22XA==,iv:+fbl7iia4Qc7/lwE2V7lJcv2opO7V+6wVahHDCwQUrY=,tag:c3/CiljPbfrb9THVB872Ag==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:i1gS1wRxvZsTVguOHgy2frqezsC4H7tcRE1IQ+N+bnr7yQMjYy/Ms3tX9DKHzvMYAxHtWzmXXFhk9PnZYl2Z5kc8/N/6qoWSgBg408bUGC7pfGnlGwP5+YgBe/yWrQzAT22mpA==,iv:IOa9PWMMJWEfYvZIMPeVP0TAfwY8Ogpnu2kp0cJA4hc=,tag:od6rqI3tbEqXrHqqoIjtfQ==,type:str]
    node_id: ENC[AES256_GCM,data:0Gu87W8ZIBPSlaMntHPvFqbBWkKpUMM78I7+NEI5eE+aEgZDfI/yV+y8d5psLoZH4xZF0WqnKmCZ+wPteWu2E/AXHewOsgK4Dvkf5BJPCNJUMsRMGRA3kA==,iv:RKF0BLuLrqpiol6kdAfo4ZpsvLuRWmg2QfDNoRme3IE=,tag:yNPBuQrmaXFgSEog/U/WEA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: bn-keys
    namespace: oem
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-10T10:55:45Z"
    mac: ENC[AES256_GCM,data:BSyNNzEEJUr2PIHM6sZABJMVIpNSRNVr3w46rjDK978TKLjU3LY5WT98p9579btH7D3+eqG9XRiwVTZ6P68Zim4rPsz3UPeHrx0VoM+mYtSjvn9mQACBnt6iemOHQ6ZUlFnY7pKMpKSvhTSU/Ji7KRp3LL3LcgyYEnhhOEjaJoU=,iv:WswBponG/MYPG0idKZBi1jyUS3fdHwR07lPXhwSHpyo=,tag:D8DkPlN5p6e56CDdw5iilg==,type:str]
    pgp:
        - created_at: "2022-02-10T10:55:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv/T5Kl1EkwoLt09rWNXWqBS5UuILd52cl5Nsz6Qe7BkbmT
            Utwh51AqEI/yFRvDaKJpl0UwB6K5Zjrl8jck6aMTF0odS3T09rEb8vjj5dPKQcat
            v3lsuBdo0gtTUR7INDZMzJPhYYokd1mf8OlfEnrDuygrnPhYVl7ldrKK0c8woItq
            mIeZC3OqNNUApNtaKe53kZkjlnuxStyfXYvcfZLJKnBNrPY/qoTPHsSYQhqP6mEC
            yfodLZzbl7Q7/83Nqfpgt+NNTDUBDnBGvRHp0n7Todh7BnZo4Vs1CyUm1bRqiohG
            90DTEbzfLk5qK1yEDhLnPIq+XR5MchHJKn3bqY3d4BxWpiYcrPCNjYVWft2DL3gw
            BZwnBMhMyl4/tq6JIRd/rEye2w8pJSnnIDa1/R7fXHgiWXpC4w5HhbipvQom7XQC
            aiEQCzyPLSqACnEKl3mihlzYema02BzJbeNqRe4SQA6O9s9D1CIaZwSwQLNV866C
            lsVva5ERrvNzVTf6Y5c40l4BbI4q9SmHJ7cl4zsiA5ufBVdi85BpZrvL59m23reu
            yFx7UCazTr1dKAx63HYlFXUjPLFvfdqLhsI8OYCsLMrjNeJzYeDymvHXHb/pYMaX
            PGeHxitTBztwkSyJJ/zt
            =5cDs
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
