apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:Uyck/ay7Fvs6Ms7z6CepnJp2hBtnjXoz9uRyo1/Kja8c1YzluBDDXc/UR6df6dtsArNgyUFGcbgm/1zWub1mDkgG7YV3PXLdsEs+HfkygbzhwKBa9eYTL5Xzxb0jKKbi9GsugJtCXFHWjQM4,iv:7A62GpoFPcdhh3FiXYqHiTnrg0HjJpK3G6MAlcWV0ew=,tag:OSL6h/q6oRRt4JmyMOeA3g==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:E5Xiw/nU8X5GjW/DqJ/+S44tZCXskVIKjQHtmxtdTvQ+MVn46zyOrY0+5cC6PNRI1og1Ve43mVyCNc9rFc/cB3j0ZfhP80f8Xp3zF0+MwnGlUkY9DjQnRT+Q1REoaX5eMvpjstTzy14=,iv:dpU514p6jZKURh7GJ+dE2XijbXZxX0fL5WOiNc24ukQ=,tag:sql+H21FLhE+Wbxdx22eJQ==,type:str]
    node_id: ENC[AES256_GCM,data:RfUKjBOSekGtpRU8dce0Hg3CvH5sx1IrzIRMKl8MojYsuQ6FzcyuVJEV8jdnSEVZOAzSMnpsk8r2h0Upj8AUz+3bqcrIiCqEVVVtdFEvcuAbwZGtgzHwFg==,iv:5BqFDmCAfBlbCCfuWJnokiiWy4tGDpxvwBslWZwB4TE=,tag:VzFHF8f18zJ4Q7q3vF93TQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: id-light-keys
    namespace: oem
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-10T10:55:45Z"
    mac: ENC[AES256_GCM,data:cSzptoo6C7x9TJrimgR41d0lyMg4ilYxdDt8A4l4uJF+dEoc7Z3C++fKDbov3l/7CmYM+NmA5SqLyVzS4Qv5xlMQWvKbwtZTisYX9XWD4mJQJdalbVbKToPwWhI1qjEU5xW0CYPq6NomWCC4SQ9DolozDpJvCRE4iTp6NCgDkHc=,iv:Wc4bdUdQK6Yf3DR0i4E1etFtMRf9RZeCXRYHOv8od6A=,tag:kpgBMxT9k3f+sJ/xbXbxrg==,type:str]
    pgp:
        - created_at: "2022-02-10T10:55:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv+JerUsJDwz75VRe9wAeQvGFac9XTMblqqaioj3ZMX1Al5
            tS/Mnc1R1eR3b42S6XWKmBRB9UOwtehjzuwOnc3bDzD+BbLx6EZh+1AuSCsU/yfp
            rb1wuobIcFIRiQvL2oFAeZyLjqluoO0B71a2xR1GYMdPLl+78xxcrI/Xilol6fDO
            iIIY7OPTjtCOaC724v0W3xpYIRIxzR0m9MuwvSnYrkVSmsWbkhbz0HGQqEjhVrtE
            90zM5PnroAx+PM/LjA7DnMS34iJ72bwUlfOOm0J6t6UmyU8hC100xUozQx2RRbxq
            i1+xnyNy6UGxZRaI+vjeTvx23xEXzntdYfYpTkIJ5LytVYBnvcY6VxdwnV8Whh1c
            cOEal0EsC7jT3ufk2WPd9c/f6oppJlpSFKFhxwhvr9fCyPHJYqbP+IhR063Jx+oP
            Mt16CJSTw9MsF14wZewUVBeg+ba1zTJSLYOxaHZg4vOe9sQ60Z79eqXNmBN3Y08r
            NgmKDyRDU7jPuLMmlZ0r0l4B7P0lzwyl4VHSG6vPzV4xIkClmaVXYg799aw9SEya
            0FGgQm0bCXkKKhjtpEUKs1357mtqhHcgEqRDwVj14QsclqSVUqdksf9c1mvBbE2p
            Qef+O04nvtDpMmoB62Wz
            =3fZ9
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
