apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:qpeXCZiDB7iTsUyybUcKlQ6CU8W5hgShbXCSDdSG73pYyNyohPsOewXoY/U8mnm8sHrgdRBU9jeeNH9/Olc/pc0x3J9IFd/YpUmjb51N+YLZCrbXkmGR5wD2VtQ=,iv:dtOrISWU5OoEzadhK5JJqSlbk6w2qPcetrsnFGNy374=,tag:vGmpX1qVYrlsuXSeHBIDXg==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:RzMMnbl3HLdZE46AOB1ctDZP3cy3h87QMuYo63omuxtQTP+O3LggNuaqZ5kUUZkhqWgjzbkANVFlSGATnb1rzYcfmXYkmati7j5/GkZgZAvb5uNHVmpoSMnRsgOpv+EfRIydEZFJP2A=,iv:LTbrwgcAtLfd3ZXSZtt9k4n1T/SwHqPnSzrPela3eSk=,tag:x5JlHDoY+cXgFh5vf4w1Eg==,type:str]
    node_id: ENC[AES256_GCM,data:1CuYVhWNl9HgqP+yvNdwjbbLw1BXV9Jk9J551Zb4os0lzJfYgcpS51t6v+b6gpjiWUscK9ZAsqe5tFjptc50nTaamMJgJA7uoaDMQgjgTo3PcOv1DWGEwQ==,iv:V+zWz+UMHfs0IrxXnvrdSgR8FYjO6vtSVasrJSLpRkM=,tag:kyH40OUULntGyou3HrGg+g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: id-light-keys
    namespace: t1
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-07T09:50:47Z"
    mac: ENC[AES256_GCM,data:6Udv1/AjpYYaL3+STiWw1l0K65X8hXiMBv8m0fjrxNO0qlrC0Lr2sHz97Ht3ifSWNL+6CgabsbLiDMxkbvaG1CEwKoU/Gyq11EOEKit8qLIJ9OMTduEX9L1GHJsBiuf3TG0+PSoc3oYFPUY9jwnef5ASE/yO99uc/1MPasgAUTE=,iv:mXVRuqtmS2insee3Ti2Kzs7CHjErPu9cigrUo3SzN8Q=,tag:sjBxTjCriaj9/bvDKRYgcQ==,type:str]
    pgp:
        - created_at: "2022-04-07T09:50:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv6Aj0VLaIqS0a2xemruR/6OyrOQ0FhSeyYYTc1UPEiSgMf
            lbKL83XAMKN9Q8F42wnbuAJjRctDH/r5oxTyUy6mRem4ijtafVhgS/bCzkMknXhJ
            i+PKOUvzexiX+UuzwXhNhpPvFX3O/X/VLWTcHdtdOhRzhsU9aycqWFMTbrNUp4II
            AnvSVtlfteUa6t/jmlFz6u2StJ3r63aygK4dDrh10v0+3hWGArodHNqyc22JPOff
            xO24s0qLmeaFn1+XTdEdWMLQ3Pbie+2G+SxhaxpAPjGRZzDlSlvIoVjyv2/DxUTO
            EXfu9ArvAoUOaa7XMTbmOGKReTJKftfBvaMnUBM3r4eNkbfXrEADxBwmRPjkLICZ
            CcWleAmit4s2+ol503kJIiJtteK6wVZ2bmw3r8yfVN1ahvh4ZNDGlBl5Zl33z02w
            aUbmOdcXQzrX7X8HELNuTxKxBXnYqXzX6UiowxTHg6Uqjl9wgbMJToDbdtLB1pWo
            pJrTil2pAf7b+DnrzyjT0l4BVztJjO4waCsmzzs0bc2fiAfCtKb5mjvJU1nzwSKi
            l/jm/UxhkC5kIHy0QT9My0UiIKDC5AaGe0/iLzg0qhoD1fB8ryYkdYkuY/A9xVH2
            oh9zNNSizWgMCxW77sNE
            =e8R3
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
