apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:IK3F1xrmm59cYBe+7hQgftXpMVa+vl4WrlqJHtf8Mpew5OpxMjMEyCUqSy9rKHJoqITKD7SzeH5z0F2qzLrdIkRNswbe3Nh6EmRFy1ZCNwNFj4MHYuTCfdjpdbt98MHn,iv:dBWUclc4xJoT6ySuJqiPalbAHEmP49lJWJpRyS+JySU=,tag:idR/6a3FsV9XA3XXJUXkew==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:Qhum7KVKwY1PRJfJC3uvJAVqOM78t1vwfx4IK6QhtmiiEaaSb0QEx33rh13SNJzv679yZIM/kqwgyEuIxeKAaUFwb7c9AzHVfzvOE+n2JpORabeA3jSFTEAcrpiaRMbAOY3iL6M0NeY=,iv:7PvbiE8AY88TXCGmsXLd7qJT6BYdNCPaxARmqTzDDOU=,tag:p8nfdOHATPWGiDM7XApecg==,type:str]
    node_id: ENC[AES256_GCM,data:V5k/r641KYlu4FHyqgW/alq6vBS9ibndE6axCcQ9nSGoyFVKZ7UDgHynidl3PEy/nglJAm2Y+mRJJ65FiBNJoyEf406kQqspxdz6Iwd5Txta+TBD+IMLrQ==,iv:UmPoVuaICcAqSt4RY8KByg8pTyDrA5/EAcY9Ewl0LIY=,tag:Gzmrv/u9VBwNJAcYLVpNmw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: id-light-keys
    namespace: t1
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-14T08:56:13Z"
    mac: ENC[AES256_GCM,data:6y+p8qCpph3yPsI5MAXddMmreydAnTDBnUxzUW453XRgw0gpzBbi8OvR6VcA+DAZwRAdQ/NXPGxVqAWwbDGKUn0kIisfH0IExusbTRjp/Je08ivIsqPaOs8eP/21Jci9+jAMNZt2l8/BlPZ4ecF1cU8dgRX4jRTUI3Xq699kLbY=,iv:MoBbSPCFqwufCdiVpp2ghoIkNRC0lX/9KjGqoRX1Kj8=,tag:I/hYkKlVclpIBTc/n8GV9Q==,type:str]
    pgp:
        - created_at: "2022-02-14T08:56:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv8DOYcLFXH2I+jG8KE5xG9CnD2UjBTk5U+cMEVd3iURyzq
            CDlOsjfYTPhq1ZuXCNqEuYlrJk7S8kdwzxyJ/+58Ed6+iP7N9ZzGF7TvNzoqK69f
            hFrFk1bPQHyqFPLUVMZ/mTBr5r+hUV/Hb2lvX7GFL/jq/qUjZyaFf3zNbD6mssah
            b8cskPW57oJZbeBZXyWbqYMT/jg5/ANhpiTdZnPruuHAGDqZf4Og6n6PqwRBmNfi
            sRd8hjGdIB71mASIjQRySM1hIrpcl4oOkUCPnm+Wj0oGT2qLFIxB5pIl0Un1Vphj
            4z3Yd5fNF+wrNtUczsaF0s1UgP6nDjjWYlbOtsT0UHOkf+UFrdvXyQ2TMUx/xbqU
            f7ZCMnWHMIriH9G58x8z9LFLqG8FA9oSlAodwrn2Etr6t1CCi//VnkmKnoEe4lUF
            bTs85tTo2q6ZuqO8qmAfeyjks929VD8gLdGfZ0byZQY6a5zAAf9AtGjJFQxsj00n
            TNgYxeZt95mzUsgHbwjs0l4BvnNGROyvVdz/ByvC46ohtzly6y9GYPN3/vvQdiZf
            l2JTdPOzCPaLOLRJBLVORujGfVwyC5Gf2NVctZUz9VNYoHW5x/T0BUsTGp4OHoIj
            apVAOax69b41Rg1ZU531
            =EIEd
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
