apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:NHK0G9AEksTRH6anINtu1zEIx3TIMA9/RXUk3EVIHbR4jCW9f/V1qYkqPebIjCvNtqy5A8d9gPSi8eK/TxpT4sv4L6XTG6pIqjBrn8xk+bGDjjapIsQZrg8gfQ9Pa+ksXE0QCHAuxe6yx+bdrQCYMw==,iv:XJjVa0kU63TM/3rqfmJg0HNt6WpcgTjEaWjnuwi4tAY=,tag:gawbdjipH3Yk+ZL0aiGLeg==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:BMSczlEJU+T9vZCIU8YeA5EPQ1Ug9xpOHPIoy6ju2Avt+NOb6YkQo0ErY33bX4fWK36UINGjeWgxIDssa/H+DlpWKFH5k2Fq3wzjw51fZf69ZRHMfpko6FqDHyJK7Wwf+dUiQ7JwTuQ=,iv:hQ3McUR6fmIniZT3wTspcCmwcB7oPg+aaJGkKBUEcyg=,tag:+m4ygPW+RoKKn17mUPYtcg==,type:str]
    node_id: ENC[AES256_GCM,data:E/bhJsdSD99dMKaWwC6d6R+2aS4ryRQe2997LmOz3vFX6Vm6gHcKBL1lVz7apCr53FE94Y+amINcg9YxNUHmDtV4u+43rKCkCvL4AqL3iM0z0frFXv9IkQ==,iv:b+1SixC9gO67/AnudbPANPZXGlL44bzSzJMOdaqpFYI=,tag:TKPH9YpiD3dMC10XdqQjfg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: id-light-keys
    namespace: t2
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-07T09:50:47Z"
    mac: ENC[AES256_GCM,data:t8BYAi0Xv9wDTHn0TnaWL1TNxFjLvlsU3ECGZjlhG0HeEA7rvB9vIk69znICbEMzEpyhkX7RkcalyKKhdns2585CIldeaYo2n1M62YR+WnehXgmokbt6QWnFMyxcsD+AWBiBOcFsNVJxxIwYxXEMc+2Q5Ph0cM/JeGm/02jXOyc=,iv:ZXrqTiNydXQc7pJBHQb84Ke0AWdg7VQ1JI4J8jRt5UM=,tag:XuC/n7SCRCOa5yzDtzF+Kg==,type:str]
    pgp:
        - created_at: "2022-04-07T09:50:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv9GC/53H/COYSRc3T2q1lvZLop870qDSacwivf2YBlzxbE
            ZAGfcvulzn4o/9HKQtGtLW5RBGkbn13rs1yrAnbhslO1nu12XgM2b7bNZpgn9LA1
            ENJqlcOXxLMqm/8Y55l7vuSvogQf13wVG9NZCgEEnTYkqzadD0WEHOorYHl08O5s
            m4jZj56JN+eYlnjCVtZAT0EPDIbm34XE9saE6u/PA9YHcD7eptivsxiOVi3iPe5h
            BaLUfXcsm5MJZz+cqFTb71BPPgSaYNNT5OeE5QucG3oUWFaM6kr4K+w8P4RaolQY
            VL9DxkvaPQPYiQW0PvidjaHi6+dEb/T1v2T+3+9af06Ruwrc5K/D81e2X92HVbxK
            8/wY/RnCLCzlvKVTH8XAQ2uezOX+hOwOKVrnhSOGSckp9x9cnLEwOAM11R3Ni3Vb
            4nE/J79gZWuQtVsGAe2iUXUiwJ3mTPUQ9WAWoKRTb4xifA2FQdckRdAm3TXPNjPc
            7OVVhWESH0mzqaWm/ZJh0l4BO4bIQU3uOb2Eqxsdb93SLFO7tb3RZAsWwk7eu9kc
            HGl3hR5kxQA0s8znRH66DCvHWjAy2DovhSk6bN991JwNcPIKk6g+sEWWnzv+i2/2
            i5oRiwbZni49s/B18WRb
            =hw1X
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
