apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:6B33GY+UMihHr33T5lPkYsDjDHaYBe6+Eq1sKtgBpr9cLAcffNsA2i4e+4p8JTESXSZSagbPg93Nqyu2f1CCR+ru8CIwbT54rlBvTYoSOGA3G+FCUgfjuGJpsud+STS5UAYsJkpbVI2JzM/V,iv:qY11R64nngtri8bk9SIokYwHOyPgGNkyfUi5GHYT2Tk=,tag:g5rAQ/g2eSobtZ6+g3YpOw==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:ntSshGpe9Rij2LNYAAxTEC3p21rBhr86Fo88l0Va8C3GXd+6S8VMi5zk97QM7Yrcgp7r5FHN4mjffumIR76weNB8z5UUgazs7H90S7+mmXL8R7N5xThdUcOoAufurKfso3dyeQRkyu0=,iv:f62uIuJMoIlJ1NnPxj4qmB8qMH/qeA92FUn2+haBgBg=,tag:fUoVjviH0gBMHoDexVA+Uw==,type:str]
    node_id: ENC[AES256_GCM,data:HAmrrgX+F4cmMiOXKKMa6XrTFCN7ospcEvZ1yiB9/H0XzUJ2Rhk3R72CXikszd+3H1MdwasEt4XHMR6l87SAfG/qNqIMbkVkdEWjRb5dAMTXKLS3fB+LhA==,iv:WMM45iI8mQNoXgTRGKKi+bwZgVYXwDbldILP5CZ3WYY=,tag:yzgmVGWoYVmD6kQLr8duXg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ipfs-bn-light-keys
    namespace: oem
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-10T10:55:46Z"
    mac: ENC[AES256_GCM,data:VifSZSTw/QOftOY5jHh0wK0f4WZ1aQaMmUJwZMrASD+CABiNxee4zs6VmNoq4eNjIuXPvN56gNcinEmXngTAKiJB/0tdkHdavHMNVpATtOZ4d6Py/dy5XL/4x/o2s0o5zqkEqLAwqLFdI2chNSbOStTY8ueeNmxE36qA6yfo0UQ=,iv:L6HkjUjQrvkTCTsjmHRxZ5WvYh2Cntt+20VF9mXpF24=,tag:zWTFk7Pz6ONGJtv8EeyhDw==,type:str]
    pgp:
        - created_at: "2022-02-10T10:55:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv9EWX/2CloFO2LpV6MTV+lHK++2viW8oweZa74E9th80/E
            Tc1N7x9NpYpexl5MuY/zBkJp1dLrt4pEyp+M9EuWJTgmj9849Fo7dkleaui1gylS
            E+BUx+3icJszWxw7mty42jCyPUgLnOBQZNLFziNzN8Ejo09taknKk6XbBlZ/Ife8
            z6f/qmIDgrqYSYCZ5LTQ9Iq9qDT6gxCtPqFfu+yK2PnSERkeuy26IaUxJM/KuxDi
            z8DhSNkwZFgdgtx8hfeho9ynu9jUTaNPBM05qM4ZHRtJgHFwV8H6Q3KUcztOkkB7
            taEmak8oSJRfci19G7dslrIv9NQny6RJTjZpVLh4ed0bYM5H1yP4mnAftWYwhIJp
            5fKkdMrCdcQVFnStxgJTUo/gSAx1r15kD6asYG+8EWYaKzimy32TTmwtlhrBgqhb
            kfEpq5gc83QBlfUniMzlgJiLXLx/tH5JUnF3DBxC5VDjDoNkJlf33oCXP9ky5N3Y
            T0JpIhkD46RaoLYVX4Vl0lwBkveIQSfBH9EGz7czKDm8EcG6FHGwEy14fN2W5MO/
            a8Xo2ku1U/y4d+56duwkrTM/aQ6tIb+GpwlPFcz/ckh6r8DPO3JJcRkW/RLU/6nP
            dcYb2RxcvW6AzJM7rA==
            =uiDL
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
