apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:mBPUviD9q5ifta1lCq7McESzZZHK24hP03ZaH5zPs8bS/c6pxDTZ5A3eAXVrUtea1cptJWYcHdVtWpCj7NkwajXz/uM39Po61LA9hsc3YBukzBP5DPosABBHvgri3egObXXZmA==,iv:WnKwFEoQVjyFbD3qUHg9TBSMKDFDKuG+VzUUkyUh+fM=,tag:Eg1FgP4yVOs/4eJzgpXEPw==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:TKJJNTPZLI5zvVu+TAsdb94FGpWdFGHatOqjwjqwLKCjmN+Flg5nLBjuXkpg3w1Q81PdWVbOJh0gbfXvTTda3Ctfr16As39ijGy/vDXCF3bHCjcGT8nv9ZXd6qtB8+Qr,iv:kAGtCW1ojMnkwCWP5a750CQ5dZk9ZkaGSQ9hJvKwaQo=,tag:pIlmN6KQ4KE0Q3ANusCHhQ==,type:str]
    node_id: ENC[AES256_GCM,data:KSCehnzV1Eua6EODsx6CFBtQK7YluEKHplC0PGW47V4M/vCwH+IIzlcZ2Ua83Jc6uJS09vtBqd0Z/ub+sWh/64/J09xm5+BoNw1rcRPhiqgk8Wjzfp6mhw==,iv:+lchDWaSJLtnLHKeHlakK+MTgl+REgbzhc9pot4smfw=,tag:o4W9gl/2BZwcbYrT2ZcS5g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: oem-1-keys
    namespace: oem
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-14T08:56:14Z"
    mac: ENC[AES256_GCM,data:lZ8706C99S8EYMzz4PAev06YVx1itswvStjVMy89O1WwCsprBR2XLV2zJYoDed9vhFyEsCKva7zRO8dia0dzbwcUm7RfK6QFDvef9o1HeFDnVQNFNWtbHQiquUNOUJlgvoYvKehur8gk+YJoALzqUdNhHUTfSD2akT6Qb3qcCSY=,iv:Nzy9wkIt/ZLTub583yubrqy44iEZ5X2ridWQjRbIhog=,tag:0Mi1Vl8wg8KjLGVDZttWMQ==,type:str]
    pgp:
        - created_at: "2022-02-14T08:56:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv/QMX/6UTux/fB4O83LDT9pXGXACPqwN3lw2D5/sRm6fEy
            KKlurQ4AaLnlQZMjGL4YsNn0vbD8wLboJPqbgDlzaaiJXqo5cWQFwvG7wRAqBDY9
            ph0xNA9KV80twwhvb0ZubuACEhmyKxYk/sjGnF/0/oS6TpQl5iANAgGVQMBJJ2B3
            9xsDs9PwlhiehVgSg9tp/5ZODjNPER8DEqCx9WnreRmRpvakWVqxROuy/dhO52Gc
            G65q1BEeOzUXUS+0NbGst5tQ1Jcmxz3R43n22KyjJxaBgla0gMk6pABG0JJD0G6e
            ijgX4GqBevrijZ0rjLT4YIOHYDpDpK6JZZhvv1XEhsm4WmTRC0yeBrKLEZ6La5Vi
            KpBXxadZzy27U0vBihv0jzHl6oi0vNkBNmhbv0FfTR8FGMZkXvQZ1ikMAPu4mQC7
            SIsMtSuy3I6hkG/TTIbJZ4KjFuuUoPRdNhRijhNdk6nOJK1Uro/O2lsD8ATB6NiO
            hNxzK0u9ppyfo6WLvhqJ0l4B3udyM8OL/JNiyuPPsebZBYsZvgIT1FgocVucAQ1v
            pOskS+FQYC/SuvjKtHCyeANg6chU0tt2p/yOErbjW3JQGyDSeleOnuJN+nH1CaNO
            e2lcitgCE5JDCnDGvOqw
            =djbi
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
