apiVersion: v1
data:
    account_seed: ENC[AES256_GCM,data:lnk1sMNgg4n8fPD0jV4vBzHrT0RnH6NSk7Khmydt9aImSDz9JbbdRP37t9y9BfxyrBSMWTdsCrYz3jg4cwJEBQ92Aqrj9pADcdbP4XBuqx9wBj6thQszJqMQPa8=,iv:AEPocCIMV4BxGn25AqiDGr45pk/XDm+9GkAX4xVFKKU=,tag:rkoa0kWqQavYOoZ8JuzYag==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: oem-keys
    namespace: oem
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-10T10:55:47Z"
    mac: ENC[AES256_GCM,data:OaQH7kcYvX1u7y1seRHWGYIggIj3pcq7eYRleSdaRRpGMJt22hQ7tvfRi3M4Qbm0R8es8hDD8CUjya0BxgTG6hP4UfZ66pBlhcvi3Nryg4eNaf7MtO4mS1N+QhV6Z09KpSmJp3uuHxIxU4YKIfUcnJD8vz5SwAtJNEanApCDBr4=,iv:RqbtWVIFQpcjGYKbDBwqcDh/6SebEA4rRPcxMAWcFlc=,tag:ZfWnPHTelmk3K5Z2mqJu1Q==,type:str]
    pgp:
        - created_at: "2022-02-10T10:55:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv+LfbwP+ppCXVmcs3/yoC3zQ5imobrFAQYoXkRVjMjkxj6
            8Et5Sn5bkuDttfqqqoASSgjgIyVGj+HZKjirgW6upVi5xy3P1pg4oXHwvDt0jxS5
            ZZeGU0cI06ob5yuiZshV2Hm01g31qp1B1vq+UT7EydQMWWRw2w9dp/Lu7t7iY+uj
            1jAtiBJ1DjjrZwSkX6AFSRdf2xmJm9LwBgBalJ7wvcKYOXshg1stOCQRHQ668E/e
            b3y4Qr1VDS/bOmybOp1825T2lAMPXPEtc2kqo1gjbuhGweJAQSUmLWhFsrnjLhoS
            DMGqoPUtuLbc48Ngbe+2YiF1T0zos7zXr0x2EeTm3dmyciPvBwwd4oAXuW+zWy7l
            uUEr7zv5+zdvi394gHvZMCuaPc9QItg22Et+uHViJti1TdWWBJhn56lRyYr4xqWm
            PTOiB27GoGxgdI325M3CiFFaeOn7cp0C/hG/UPs7GfIiDXp0oBnhpmYoRh8udwWR
            hCT9kciCQ3koxFUetZD90lwBnPWQrIY/q8Uh4mnfazN9/f5E0jzlu6b2lexN62jS
            oz67s9mzBoNd1O+VEHDLpPDr5rc7jyACBB63poq6jZrVvjQKW/J8JHbqkIHgyPDz
            wpQtW9TZO2aZRcS+MA==
            =mdAy
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
