apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:sWco7W9M+C0RhbSo5ORZvtqf+8n9pUSi0kl0noxs2KFclC0n8UENv8B9TdSLTtPwq7skN53a6WZx+k0mkpjFv89VsxSlFp2qQ5P7brrmY6HWE/NPoiFc+bFPEf1CaBi4ieoUfQ==,iv:wKOWN+0wraEUgcjVm8uAeEXgrBCPIJ1WL7CD94P9mO4=,tag:ZdrXg1wQDQ7ZebKRvIs4OQ==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:KJucr/lb3qAyZjk3U6jJwu9PI3ok4EkaR24I21b/34mzomeLxLjWJzjxQ/l8nF8HCGs2DYPDXjSuu/LkDLZAa3xlbD/s3rGh09stvWBLsjxfOzk6yvBWTxNaFZDVlaOL,iv:XOGNcBm7GaLlauLaIXSLrQon7076rJ6xNk6jqvwhpOQ=,tag:HpZxtymKzg34KwQiU6FTPA==,type:str]
    node_id: ENC[AES256_GCM,data:Ci+X3ai155RGzUppOFc2PskpgfPdpBUOAGtqMXbSg3qA5IQwlvkuAmtBeU8FXettLQCBTooL1gETFhxTL7EpBSOzM79IMw2dA41GgFX0KqZGR8WCDnL0MQ==,iv:WRGjz7m1cf9WXAbXLwqC0WvZbwNYvLRxcniMteXzeb4=,tag:8g+jEGGofXu6razRyEhXtA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: t1-0-keys
    namespace: t1
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-10T10:55:47Z"
    mac: ENC[AES256_GCM,data:F4XtFrHdL9WWiYo2wkPjpnjC0JFZAh3FkqLp3FvwTBnvZtqMo3h8CZS5znMC9Gr6uL58Wm/ySdroRSLWbJrupUBlWmdUvml9qPB6w3G49EC1gtaaAQx520QCMihAeddZUiExFXaxLVKfSxh2YBoL2j0G5wNHJftfq1cNicU8pww=,iv:9R4WVlaYP3hPYqEtgZOE+0V02ya10mGwHQ5NI2osaLo=,tag:0QZbTCWWcxalhfVvn/+2WA==,type:str]
    pgp:
        - created_at: "2022-02-10T10:55:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQwAqDLmYOkxP31osjJGkJQSkHIyAWPTXLnkkg4TsYJEGqbI
            Xcdhc1bT+dT26CHAcJ7zYzTy5kmxTezQ+TpZS1sWfJW0W86sOaKxUEwAmjpUu0XN
            KYFUleUljLVza9wU9Qeu8bhpZygj3cqSSiBSsLYVQI3+oDVbneKn1pVP0RsWlEuz
            JuUT9XkE17zZleYVersZUAfrAqJlXLHtIaFUa/7U/diA5Y+9q+lvi5Rbc3dsFh3p
            CthTGo/6GugIre1U3zU1raEM89jt76K5qG8630hWc5RlrArGe7a3S22BrJasSEvM
            XEWtGbF0jSm51FvFglAJOPYaxFptFAjK0IKisVYS9PYta0d0UPuo4mwywewlEUrE
            58nBGVFcpG2n9ERyDxYB484DKGWmuvTQ1X2Zc/vwOddIkxzvRb22u8wc75sJy2oe
            UAfG6B4vb6GxTqd8D9wqcb7uXI8LfqWaCP4UAx4M+fMleAWil5Uqq986dJki6OXR
            j7CMFtnZNbeISI1MixCH0l4BtqWH8xzzzreqcA1Kb3ZvPerFXiUtFoY+a8ELTYJy
            17yuGAlXt2WVVrq16Hlnl0s3kCkYZhxVM8dtNK4ESmuH69EvKwEN0/3zBDW149Wu
            HBOqzDph2JEMqb7DMr7P
            =YmEV
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
