apiVersion: v1
data:
    account_seed: ENC[AES256_GCM,data:Sw1yLmIrTOIFGFf1dEjXgWai9d3EMlSFAOwTZz+DyVeI/s4beNsgj0wj6euYHn8ZAw6dQurIE+6VENEEYrFHSTbXrKaq7mNySTNMCs/NyOSuLVU84qcEDK+1PQrMZnjF,iv:uiO/hLn/LRoRnmeWsVbUu9dqa5X0sxosNfg0BBIZHys=,tag:1z6JubcQBnV4I1hgPJ2gOw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: t1-keys
    namespace: t1
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-14T08:56:15Z"
    mac: ENC[AES256_GCM,data:xALHup8JKL7VPOR578Meoz1oHSniOgUSDulx8afCG6ag6mmDWFwsG/lcP5kktPPc8x90nahTNFlfeNLItUPQHTeiVWF+tHAUvD6Lv0VABl7b9EspPQdOVyNXVL8AsbTqWnkj5lLVEztclSlp+gGImOLZZCCxty71LV4NwQbO7lI=,iv:pO7UcNXeihmPm6arUcXeyQkQP/IqIa5uf6gu4PSqF1E=,tag:ISnTRAeqFQa89BEf3ZYppA==,type:str]
    pgp:
        - created_at: "2022-02-14T08:56:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA80qvHKdsLbXAQv/Q0DUmcchqkaLm2qcOPuvZZNJOn6x/qq8q3wyPysc19le
            J/7g6tH3E03p775iU3+KP0o4of7b651CItiuwzVmmcaxpwQyehw6EU42792C42nX
            5Q5Dum06zVUv2nLoQH95byH01PGLiKVIYUhS8iyzBRGUfHPu+N/781wY4cB+tmFb
            yvDsqSHDsoDW6bD2NVWeanng1GA0AR9lUMtHUi63ZoG1jA9smbngMLzIRwEcyG79
            qANW1RFo44hHe5muh8IyrDAjzrnR5QJOjcJH/0mVyrrFgN8SwX3dk+RjA1UJViPM
            OVVx/vq1HtO6lL7rgb5/kp2Sts+vZC6thRxhHstXCD6PLSXo9TkXm9E6wOnon4X7
            f6s4oDOG+htE+BTSUyz+LiiGLOOAX0N8Qqi8WV+6tB+2rH7wq5JCPHtj01vKkBF5
            YtDsjcMppICbXO6ccO5iHE4nuB7MsXh4Z2It6ubViRqJd8v4cbzBc/ZsQyIMCIRB
            1o81+21Wwl1zdzRx3IXJ0lwBuVIEbhwNsa6Cblj3iMjIKBM5n0tLIpripur1Xtb1
            +7A1nUI2t5aQJrGeerkfeSgVSF2190pnh5e5spMEfAgsjtnTHAPLH1vLOo3YWMvV
            gU+EzhY2DxPsIAuaGw==
            =ldBU
            -----END PGP MESSAGE-----
          fp: AF73310D7745761A4014FF8F12C8076653BBA9D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
