---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bob-node
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: sqnc-node
      version: "4.2.1"
      sourceRef:
        kind: HelmRepository
        name: sqnc-node
  valuesFrom:
  - kind: ConfigMap
    name: bob-values
    valuesKey: values-sqnc-node.yaml
  interval: 10m
