node:
  chain: local
  role: validator
  dataVolumeSize: 100Gi
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  keys:
    - type: "babe"
      scheme: "sr25519"
    - type: "gran"
      scheme: "ed25519"

  flags:
    - "--rpc-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"
    - "--prometheus-external"
storageClass: managed-csi-premium
