service:
  type: ClusterIP
ingressClassResource:
  name: nginx-bob
scope:
  enabled: true
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Equal
containerPorts:
  http: 80
  https: 443
  metrics: 10254
