node:
  chain: local
  role: validator
  dataVolumeSize: 5Gi
  customNodeKey: "0000000000000000000000000000000000000000000000000000000000000001"
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  flags:
    - "--rpc-external"
    - "--ws-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-ws-external"
    - "--unsafe-rpc-external"
    - "--alice"
storageClass: standard
