apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring
  namespace: dscp
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
    grafana:
      persistence:
        enabled: true
      plugins:
        - camptocamp-prometheus-alertmanager-datasource
      additionalDataSources:
        - name: "Prometheus AlertManager"
          type: camptocamp-prometheus-alertmanager-datasource
          uid: prometheus-alertmanager
          url: http://{{ template "kube-prometheus-stack.fullname" . }}-alertmanager.{{ template "kube-prometheus-stack.namespace" . }}:{{ .Values.alertmanager.service.port }}/{{ trimPrefix "/" .Values.alertmanager.alertmanagerSpec.routePrefix }}
          access: proxy
          isDefault: false
          jsonData:
            timeInterval: 30s
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'polkadot'
            orgId: 1
            folder: 'Polkadot'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/polkadot
          - name: 'postgres'
            orgId: 2
            folder: 'Postgres'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/postgres
          - name: 'nginx'
            orgId: 3
            folder 'NginX'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/nginx
      dashboards:
        polkadot:
          polkadot:
            gnetId: 13840
            revision: 4
            datasource:
            - name: DS_PROMETHEUS_ALERTMANAGER
              value: "Prometheus AlertManager"
            - name: DS_PROMETHEUS
              value: "Prometheus"
        postgres:
          postgres:
            url: https://github.com/lstn/misc-grafana-dashboards/blob/master/dashboards/postgresql-database.json
            datasource:
            - name: DC_PROMETHEUS
              value: "Prometheus"
        nginx:
          nginx:
            gnetId: 15827
            revision: 1
            datasource:
            - name: DS_PROMETHEUS
              value: "Prometheus"

