apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring
  namespace: dscp
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
    grafana:
      dashboards:
        default:
          polkadot:
            gnetID: 13840
            revision: 4
            datasource: Prometheus
