apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring
  namespace: dscp
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
    grafana:
      persistence:
        enabled: true
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: 'Polkadot'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          polkadot:
            gnetID: 13840
            revision: 4
            datasource: Prometheus
