apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring
  namespace: dscp
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
    grafana:
      persistence:
        enabled: true
      plugins:
        - camptocamp-prometheus-alertmanager-datasource
      additionalDataSources:
        - name: promethus-alertmanager
          type: prometheus
          uid: prometheus-alertmanager
          url: http://{{ template "kube-prometheus-stack.fullname" . }}-prometheus.{{ template "kube-prometheus-stack.namespace" . }}:{{ .Values.prometheus.service.port }}/{{ trimPrefix "/" .Values.prometheus.prometheusSpec.routePrefix }}
          access: proxy
          isDefault: false
          jsonData:
            timeInterval: 30s
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: 'Polkadot'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          polkadot:
            gnetID: 13840
            revision: 4
            datasource: Prometheus
