apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: order
resources:
  - blue-node
  - cyan-node

  - source.yaml
configMapGenerator:
  - name: order-values
    files:
      - values-blue.yaml=blue-node/values.yaml
      - values-cyan.yaml=cyan-node/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
