apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: capacity
resources:
  - magenta-node
  - red-node
  - ipfs-node
  - sqnc-identity-service
  - source.yaml
configMapGenerator:
  - name: capacity-values
    files:
      - values-magenta.yaml=magenta-node/values.yaml
      - values-red.yaml=red-node/values.yaml
      - values-ipfs.yaml=ipfs-node/values.yaml
      - values-sqnc-identity-service.yaml = sqnc-identity-service/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
