apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: capacity
resources:
  - magenta-node
  - source.yaml
configMapGenerator:
  - name: capacity-values
    files:
      - values-magenta.yaml=magenta/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
