apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-values
  namespace: dscp
data:
  values.yaml: |
    configmap:
      hashSumEnabled: true

    service:
      proxy:
        enabled: false
    oathkeeper:
      config:
        log:
          level: debug
          format: json
        access_rules:
          repositories:
            - file:///etc/rules/access-rules.json
        serve:
          api:
            port: 4456
          prometheus:
            port: 9000
        errors:
          fallback:
            - json
          handlers:
            json:
              enabled: true
              config:
                verbose: true
        authenticators:
          oauth2_introspection:
            enabled: true
            config:
              introspection_url: http://hydra-admin/oauth2/introspection
              scope_strategy: wildcard
      access_rules:
        - id: some-id
          match:
            url: http://localhost/api/
            methods:
            - GET
            - POST
          authenticators:
          - handler: oauth2_introspection
            config: {}
          authorizer:
            handler: allow
          mutators:
          - handler: noop
          
    ingress:
      proxy:
        enabled: false
      api:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/use-regex: "true"
          nginx.ingress.kubernetes.io/rewrite-target: /$1
        hosts:
          - host: localhost
            paths:
              - path: /oathkeeper/(.*)
                pathType: ImplementationSpecific
    maester:
      enabled: false
