apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: oathkeeper-example
  namespace: dscp
spec:
  match:
    url: blah.com
    methods:
      - GET
      - POST
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
