apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1m
  chart:
    spec:
      chart: loki-stack
      version: "2.8.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
      valuesKey: values.yaml
