test_pod:
  enabled: false
grafana:
  enabled: true # Enable Grafana for visualization
  adminPassword: admin # Customize the admin password if needed
  sidecar:
    datasources:
      label: ""
      labelValue: ""
      enabled: true
      maxLines: 1000
  image:
    tag: 10.3.3 # Grafana image version (optional, can leave as default)
