loki:
  commonConfig:
    replication_factor: 1 # Set replication_factor to 1 for a single replica deployment
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # Retain logs for 28 days
  compactor:
    retention_enabled: true
    delete_request_store: s3
  ruler:
    enable_api: true

minio:
  enabled: true # Enable MinIO for object storage if required

chunk_cache:
  enabled: false

gateway:
  enabled: false

results_cache:
  enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1 # Deploy a single replica of Loki

# Zero out replica counts for other components since you're using single binary mode
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
