apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: charlie
resources:
  - source.yaml
  - sqnc-node
configMapGenerator:
  - name: charlie-values
    files:
      - values-sqnc-node.yaml=sqnc-node/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
