externalSqncNode:
  host: blue-node-sqnc-node-0
  port: 9944

  ### Need the below?
ipfs:
  privateKey: CAESQLfNGaEqtlj1juOeV1/yqS2RxYIXFCnSffHqmRDQtMyGZ5nW90T0ULaquqNLe6waWAu6154bKsIqanNezT+m+sg=
  publicKey: 12D3KooWGnnDccXt956NhFkUki48216AwogbfWTcN33mjinFkNNT

  ###
persistence:
  storageClass: managed-csi-premium ## Correct storage class?
sqncNode:
  enabled: false
