---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vouch
  namespace: kube-system
spec:
  install:
    remediation:
      retries: -1
  releaseName: vouch
  chart:
    spec:
      chart: vouch
      sourceRef:
        kind: HelmRepository
        name: vouch
  interval: 10m0s
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: vouch-proxy-values
      valuesKey: values.yaml
