logLevel: info
paths:
  - http://alice-identity-service-sqnc-identity-service:3000/api-docs
  - http://alice-sqnc-matchmaker-api:3000/api-docs
baseUrl:
  - http://localhost:3080/alice/
apiPublicUrlPrefix: /alice
oauthClientId: "account-console"
oauthAppName: "Account Console"
oauthUsePkce: true
ingress:
  hostname: localhost
  paths:
    - path: /alice/(api-docs(/.*)?)
      pathType: Prefix
    - path: /alice/(swagger(/.*)?)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
securitySchema:
  name: "oauth2"
  type: "oauth2"
  enabled: true
  oauth2:
    flows:
      - authorizationCode
      - clientCredentials
    authorizationUrl: "/auth/realms/simple/protocol/openid-connect/auth"
    tokenUrl: "/auth/realms/simple/protocol/openid-connect/token"
    refreshUrl: "/auth/realms/simple/protocol/openid-connect/token"
    scopes: {}
