node:
  chain: inteli-stage
  role: validator
  dataVolumeSize: 30Gi
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  keys:
    - type: aura
      scheme: sr25519
    - type: gran
      scheme: ed25519
  flags:
    - "--rpc-external"
    - "--ws-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-ws-external"
    - "--unsafe-rpc-external"
    - "--bootnodes '/dns4/oem-bn-dscp-node-0-rc-p2p.oem.svc.cluster.local/tcp/30333/p2p/12D3KooWQSy2rqKyrkyqnniFkLg3A8UFn6ChLBoRxj4LRoyGgUnf'"
image:
  tag: v3.0.0
storageClass: ebs-sc-substrate