config:
  logLevel: info
  dscpApiHost: alice-dscp-api
  identityServiceHost: alice-identity-service-dscp-identity-service
  auth:
    jwksUri: https://inteli.eu.auth0.com/.well-known/jwks.json
    audience: inteli-dev
    issuer: https://inteli.eu.auth0.com/
    tokenUrl: https://inteli.eu.auth0.com/oauth/token
ingress:
  paths:
    - "/alice/inteli-api/(.*)"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-url: "http://oathkeeper-api.dscp.svc.cluster.local:4456/decisions"
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Original-URL $request_uri;
      proxy_set_header X-Forwarded-Method $request_method;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Uri $request_uri;
