---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: capacity-matchmaker-api
  namespace: capacity
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: ipfs-capacity
    - name: capacity-identity-service
  version: 2.0.1
  chart:
    spec:
      chart: sqnc-matchmaker-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: capacity-values
      valuesKey: values-matchmaker-api.yaml
    - kind: Secret
      name: capacity-matchmaker-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password
  interval: 10m0s
