logLevel: info
userUri: 5Gh5cFC3sPS7pK8SN41Ytp6VFsMyPpvKxtrrcLpkf19u9W83
externalSqncNode:
  host: magenta-sqnc-node-0
  port: 9944
externalSqncIpfs:
  host: ipfs-capacity-sqnc-ipfs-api
  port: 5001
externalSqncIdentity:
  host: capacity-identity-service-sqnc-identity-service
  port: 3000
authType: EXTERNAL
ingress:
  enabled: false
  ingressClassName: nginx-capacity
  hostname: capacity.dsch-l3.com
node:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 15Gi
