---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: ambassador
spec:
  releaseName: traffic-manager
  chart:
    spec:
      chart: telepresence
      sourceRef:
        kind: HelmRepository
        name: datawire
        namespace: ambassador
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: traffic-manager-config
