name: validate-kind-e2e

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #   branches:
  #     - 'renovate/**'
  push:
    branches:
      - feature/add_e2e_kind_action

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Init Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Flux
        run: |
          brew install fluxcd/tap/flux@2.3
          flux -v
      - name: Init Kind action
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: sqnc-flux-infra
      - name: Install Flux to cluster
        run: flux install
      - name: Source repository and reconcile
        run: |
          flux create source git flux-system \
          --url=${{ github.event.repository.html_url }} \
          --branch=${GITHUB_REF#refs/heads/} \
          --username=${GITHUB_ACTOR} \
          --password=${{ secrets.GITHUB_TOKEN }}
          flux create kustomization flux-system \
          --source=flux-system \
          --path=./clusters/kind-cluster/base
      - name: Verify Flux kustomizations
        run: |
          kubectl -n kube-system wait kustomization/nginx-sync --for=condition=ready --timeout=10m
          kubectl -n keycloak wait kustomization/keycloak-sync --for=condition=ready --timeout=10m
          kubectl -n monitoring wait kustomization/monitoring-sync --for=condition=ready --timeout=10m
          kubectl -n loki wait kustomization/promtail-sync --for=condition=ready --timeout=10m
          kubectl -n loki wait kustomization/loki-sync --for=condition=ready --timeout=10m
          kubectl -n alice wait kustomization/alice-sync --for=condition=ready --timeout=10m
          kubectl -n bob wait kustomization/bob-sync --for=condition=ready --timeout=10m
          kubectl -n charlie wait kustomization/charlie-sync --for=condition=ready --timeout=10m
      - name: Verify Helm releases
        run: |
          kubectl -n kube-system wait helmrelease --all --for=condition=ready --timeout=10m
          kubectl -n keycloak wait helmrelease --all --for=condition=ready --timeout=10m
          kubectl -n monitoring wait helmrelease --all --for=condition=ready --timeout=10m
          kubectl -n loki wait helmrelease --all --for=condition=ready --timeout=10m
          kubectl -n alice wait helmrelease --all --for=condition=ready --timeout=10m
          kubectl -n bob wait helmrelease --all --for=condition=ready --timeout=10m
          kubectl -n charlie wait helmrelease --all --for=condition=ready --timeout=10m
      # - name: Comment with test results
      #   run: |
      #     node="alice"
      #     echo "test results for $node/sqnc-node-test-suite:\n" >> comment.txt
      #     kubectl logs -n $node job/$node-node-sqnc-node-0-post-install-test-suite >> comment.txt
      #     echo "test results for $node/sqnc-matchmaker-api-test-suite:\n" >> comment.txt
      #     kubectl logs -n $node job/$node-sqnc-matchmaker-api-test-suite >> comment.txt
      #     gh pr comment ${{ github.event.number }} --body-file comment.txt
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      - name: Debug Flux controller state
        if: failure()
        run: |
          kubectl -n flux-system get all
      - name: Debug source-controller logs
        if: failure()
        run: |
          kubectl -n flux-system logs deploy/source-controller
      - name: Debug kustomize-controller logs
        if: failure()
        run: |
          kubectl -n flux-system logs deploy/kustomize-controller
      - name: Debug helm-controller logs
        if: failure()
        run: |
          kubectl -n flux-system logs deploy/helm-controller
      - name: Report all resources
        if: failure()
        run: |
          flux get all --all-namespaces
      - name: get all svc
        if: failure()
        run: kubectl get svc -n kube-system
